version: '3'

services:
  chatserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9081:9081

  chatclient:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3.7.4
