version: '3'

services:
  chatserver:
    build: ./server/
    container_name: chatserver
    ports:
      - 9081:9081

  chatclient:
    build: ./client/
    volumes:
      - "./client:/usr/app"
    ports:
      - 8080:8080

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
