version: '3'

services:
  chatserver:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9081:9081

  chatclient:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
      
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
      